# action.yml
name: 'AWS Elastic Beanstalk cli deployment for github actions'

author: Arslan Javaid

description: 'Provide eb cli commands for github actions'

branding:
  icon: 'terminal'  
  color: 'black'
  
inputs:
  command: 
    description: 'eb <command>'
    required: true
    default: 'deploy'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
